/*************************************************************************************/
/*      Copyright 2009 Barcelona Supercomputing Center                               */
/*                                                                                   */
/*      This file is part of the NANOS++ library.                                    */
/*                                                                                   */
/*      NANOS++ is free software: you can redistribute it and/or modify              */
/*      it under the terms of the GNU Lesser General Public License as published by  */
/*      the Free Software Foundation, either version 3 of the License, or            */
/*      (at your option) any later version.                                          */
/*                                                                                   */
/*      NANOS++ is distributed in the hope that it will be useful,                   */
/*      but WITHOUT ANY WARRANTY; without even the implied warranty of               */
/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                */
/*      GNU Lesser General Public License for more details.                          */
/*                                                                                   */
/*      You should have received a copy of the GNU Lesser General Public License     */
/*      along with NANOS++.  If not, see <http://www.gnu.org/licenses/>.             */
/*************************************************************************************/

#ifndef _NANOS_OMP_H_
#define _NANOS_OMP_H_

#include "nanos.h"
#include "omp.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _MERCURIUM
// define OpenMP API version
#pragma nanos interface family(openmp) version(5)
#endif

#define NANOS_OMP_WS_TSIZE 5

nanos_err_t nanos_omp_single ( bool *);
nanos_err_t nanos_omp_barrier ( void );

void nanos_omp_set_interface ( void * );
nanos_err_t nanos_omp_set_implicit ( nanos_wd_t uwd );

/* API calls that are generated by the compiler */
int nanos_omp_get_max_threads ( void );

nanos_ws_t nanos_omp_find_worksharing( omp_sched_t kind );
nanos_err_t nanos_omp_get_schedule ( omp_sched_t *kind, int *modifier );

#ifdef __cplusplus
}
#endif

#endif
