/*************************************************************************************/
/*      Copyright 2009 Barcelona Supercomputing Center                               */
/*                                                                                   */
/*      This file is part of the NANOS++ library.                                    */
/*                                                                                   */
/*      NANOS++ is free software: you can redistribute it and/or modify              */
/*      it under the terms of the GNU Lesser General Public License as published by  */
/*      the Free Software Foundation, either version 3 of the License, or            */
/*      (at your option) any later version.                                          */
/*                                                                                   */
/*      NANOS++ is distributed in the hope that it will be useful,                   */
/*      but WITHOUT ANY WARRANTY; without even the implied warranty of               */
/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                */
/*      GNU Lesser General Public License for more details.                          */
/*                                                                                   */
/*      You should have received a copy of the GNU Lesser General Public License     */
/*      along with NANOS++.  If not, see <http://www.gnu.org/licenses/>.             */
/*************************************************************************************/

#ifndef _NANOS_OMP_H_
#define _NANOS_OMP_H_

#include "nanos.h"
#include "nanos_reduction.h"

typedef enum nanos_omp_sched_t {
   omp_sched_static = 1,
   omp_sched_dynamic = 2,
   omp_sched_guided = 3,
   omp_sched_auto = 4
} nanos_omp_sched_t;

#ifdef __cplusplus
extern "C" {
#endif

#define NANOS_OMP_WS_TSIZE 5

NANOS_API_DECL(nanos_err_t, nanos_omp_single, ( bool *));
NANOS_API_DECL(nanos_err_t, nanos_omp_barrier, ( void ));

void nanos_omp_set_interface ( void * );
NANOS_API_DECL(nanos_err_t, nanos_omp_set_implicit, ( nanos_wd_t uwd ));

/* API calls that are generated by the compiler */
NANOS_API_DECL(int, nanos_omp_get_max_threads, ( void ));
NANOS_API_DECL(int, nanos_omp_get_num_threads, ( void ));
NANOS_API_DECL(int, nanos_omp_get_thread_num, ( void ));

NANOS_API_DECL(nanos_ws_t, nanos_omp_find_worksharing, ( nanos_omp_sched_t kind ));
NANOS_API_DECL(nanos_err_t, nanos_omp_get_schedule, ( nanos_omp_sched_t *kind, int *modifier ));

#ifdef __cplusplus
}
#endif

#endif
