
paraver_config_files = \
     paraver_configs/hwc/papi/program/Load_stores.cfg\
     paraver_configs/hwc/papi/program/branch_mix.cfg\
     paraver_configs/hwc/papi/program/Stores.cfg\
     paraver_configs/hwc/papi/program/flops.cfg\
     paraver_configs/hwc/papi/program/Loads.cfg\
     paraver_configs/hwc/papi/program/instructions.cfg\
     paraver_configs/hwc/papi/program/3dh_instr_state.cfg\
     paraver_configs/hwc/papi/program/Loads_to_FMA_ratio.cfg\
     paraver_configs/hwc/papi/program/Computation_intensity.cfg\
     paraver_configs/hwc/papi/program/useful_instructions.cfg\
     paraver_configs/hwc/papi/program/Load2store_ratio.cfg\
     paraver_configs/hwc/papi/models/3D_duration.cfg\
     paraver_configs/hwc/papi/performance/2dh_ipc_frequency.cfg\
     paraver_configs/hwc/papi/performance/L2Dmisses_rate.cfg\
     paraver_configs/hwc/papi/performance/useful_cycus.cfg\
     paraver_configs/hwc/papi/performance/MFMAS.cfg\
     paraver_configs/hwc/papi/performance/useful_MIPS.cfg\
     paraver_configs/hwc/papi/performance/cycles_per_us_decentInterval.cfg\
     paraver_configs/hwc/papi/performance/CPI.cfg\
     paraver_configs/hwc/papi/performance/MemBW_perprocess.cfg\
     paraver_configs/hwc/papi/performance/NoIssue_cycles_per_us.cfg\
     paraver_configs/hwc/papi/performance/MIPS.cfg\
     paraver_configs/hwc/papi/performance/3dh_cycles_per_us.cfg\
     paraver_configs/hwc/papi/performance/IPC.cfg\
     paraver_configs/hwc/papi/performance/MLoadS.cfg\
     paraver_configs/hwc/papi/performance/MFLOPS.cfg\
     paraver_configs/hwc/papi/performance/MemBW_pernode.cfg\
     paraver_configs/hwc/papi/performance/cycles_per_us.cfg\
     paraver_configs/hwc/papi/architecture/L1_store_misses.cfg\
     paraver_configs/hwc/papi/architecture/L1D_misses.cfg\
     paraver_configs/hwc/papi/architecture/useful_loadad_bytes.cfg\
     paraver_configs/hwc/papi/architecture/L1_Load_missratio.cfg\
     paraver_configs/hwc/papi/architecture/loaded_bytes.cfg\
     paraver_configs/hwc/papi/architecture/L3D_misses.cfg\
     paraver_configs/hwc/papi/architecture/Relative_preempted_time.cfg\
     paraver_configs/hwc/papi/architecture/L1_Load_misses.cfg\
     paraver_configs/hwc/papi/architecture/L3D_miss_ratio.cfg\
     paraver_configs/hwc/papi/architecture/relative_preemption_time.cfg\
     paraver_configs/hwc/papi/architecture/3dh_percentpreempted_useful.cfg\
     paraver_configs/hwc/papi/architecture/TLB_missratio.cfg\
     paraver_configs/hwc/papi/architecture/3dh_preempted_useful.cfg\
     paraver_configs/hwc/papi/architecture/L2D_misses.cfg\
     paraver_configs/hwc/papi/architecture/L2D_Total_miss_ratio.cfg\
     paraver_configs/hwc/papi/architecture/L1D_missratio.cfg\
     paraver_configs/hwc/papi/architecture/TLB_misses.cfg\
     paraver_configs/hwc/papi/architecture/Preempted_time.cfg\
     paraver_configs/hwc/papi/architecture/2dh_preemption_time.cfg\
     paraver_configs/hwc/papi/architecture/L2D_miss_ratio.cfg\
     paraver_configs/hwc/papi/architecture/L1_2_L2_miss_ratio.cfg\
     paraver_configs/hwc/papi/architecture/L2_2_TLB_miss_ratio.cfg\
     paraver_configs/hwc/papi/architecture/BytesPerFlop.cfg\
     paraver_configs/hwc/papi/architecture/L2D_miss_ratio_v2.cfg\
     paraver_configs/hwc/papi/architecture/3dh_IPC_state.cfg\
     paraver_configs/hwc/papi/architecture/useful_loaded_bytes.cfg\
     paraver_configs/hwc/papi/architecture/JS21_relative_preempted_time.cfg\
     paraver_configs/hwc/papi/architecture/BytesPerInstr.cfg\
     paraver_configs/hwc/papi/architecture/L3_misses.cfg\
     paraver_configs/hwc/papi/architecture/2dh_L1D_total_misses.cfg\
     paraver_configs/hwc/papi/architecture/2dh_L2_total_misses.cfg\
     paraver_configs/hwc/papi/architecture/2dh_TLB_total_misses.cfg\
     paraver_configs/hwc/papi/mx_counters/nb_medium_msgs_sent.cfg\
     paraver_configs/hwc/papi/mx_counters/route_dispersion.cfg\
     paraver_configs/hwc/papi/mx_counters/nb_small_msgs_sent.cfg\
     paraver_configs/hwc/papi/mx_counters/nb_rndv_msgs_sent.cfg\
     paraver_configs/hwc/active_set.cfg\
     paraver_configs/mpi/analysis/2dc_connectivity_bw.cfg\
     paraver_configs/mpi/analysis/3dh_size_call.cfg\
     paraver_configs/mpi/analysis/point2point/3dc_msgsize_totbytes.cfg\
     paraver_configs/mpi/analysis/point2point/2dh_p2p_phase_duration.cfg\
     paraver_configs/mpi/analysis/point2point/2d_comm_pattern.cfg\
     paraver_configs/mpi/analysis/point2point/3dc_srbw_bytes.cfg\
     paraver_configs/mpi/analysis/point2point/3dh_srbw_per_call.cfg\
     paraver_configs/mpi/analysis/point2point/2dh_send_size.cfg\
     paraver_configs/mpi/analysis/point2point/3dh_bw_per_call.cfg\
     paraver_configs/mpi/analysis/point2point/3dh_msgsize_per_pt2pt_call.cfg\
     paraver_configs/mpi/analysis/point2point/IProbe_density.cfg\
     paraver_configs/mpi/analysis/point2point/2d_comm_pattern_snd_order.cfg\
     paraver_configs/mpi/analysis/point2point/system_bw.cfg\
     paraver_configs/mpi/analysis/point2point/2d_who_latesends_to_whom.cfg\
     paraver_configs/mpi/analysis/point2point/2d_costofreceives_per_source.cfg\
     paraver_configs/mpi/analysis/point2point/2d_comm_pattern_rcv.cfg\
     paraver_configs/mpi/analysis/point2point/2d_who_comms.cfg\
     paraver_configs/mpi/analysis/point2point/2dp_high_bw_process.cfg\
     paraver_configs/mpi/analysis/point2point/3dh_cost_per_call.cfg\
     paraver_configs/mpi/analysis/point2point/2d_comm_pattern_snd.cfg\
     paraver_configs/mpi/analysis/other/System_BW.cfg\
     paraver_configs/mpi/analysis/other/Collective_stats.cfg\
     paraver_configs/mpi/analysis/other/3dh_bw_per_call.cfg\
     paraver_configs/mpi/analysis/other/Collective_LateArrivers.cfg\
     paraver_configs/mpi/analysis/other/3dc_p2p_size_bw_per_call.cfg\
     paraver_configs/mpi/analysis/other/3dc_size_bw_per_call.cfg\
     paraver_configs/mpi/analysis/other/call_duration_histogram.cfg\
     paraver_configs/mpi/analysis/other/3dh_duration_per_call.cfg\
     paraver_configs/mpi/analysis/other/Collectives_balance.cfg\
     paraver_configs/mpi/analysis/other/MPIxroutine.cfg\
     paraver_configs/mpi/analysis/other/CommComp_overlap.cfg\
     paraver_configs/mpi/analysis/other/Specific_collective_analysis.cfg\
     paraver_configs/mpi/analysis/other/communication_matrix.cfg\
     paraver_configs/mpi/analysis/other/CostOf_p2pCalls.cfg\
     paraver_configs/mpi/analysis/other/Correlation_duration_size.cfg\
     paraver_configs/mpi/analysis/2dp_MPI_activity.cfg\
     paraver_configs/mpi/analysis/avg_netbw.cfg\
     paraver_configs/mpi/analysis/2dp_connectivity.cfg\
     paraver_configs/mpi/analysis/2dh_bytes_sent.cfg\
     paraver_configs/mpi/analysis/3dh_duration_per_call.cfg\
     paraver_configs/mpi/analysis/3dh_duration_MPI_activity.cfg\
     paraver_configs/mpi/analysis/3dc_connectivity_caller.cfg\
     paraver_configs/mpi/analysis/2dp_mpi_stats.cfg\
     paraver_configs/mpi/analysis/advanced/2dc_e2ebw_bytes.cfg\
     paraver_configs/mpi/analysis/advanced/2dc_connectivity_snd_bytes.cfg\
     paraver_configs/mpi/analysis/advanced/2dp_totbytessent.cfg\
     paraver_configs/mpi/analysis/advanced/2dc_bytessent_totbytessent.cfg\
     paraver_configs/mpi/analysis/advanced/2dh_comm_phase_duration.cfg\
     paraver_configs/mpi/analysis/collectives/3dh_duration_collective.cfg\
     paraver_configs/mpi/analysis/collectives/3dh_recvsize_collectivecall.cfg\
     paraver_configs/mpi/analysis/collectives/3dh_sendsize_collectivecall.cfg\
     paraver_configs/mpi/scalasca_properties/received_from_delayed.cfg\
     paraver_configs/mpi/scalasca_properties/late_receivers.cfg\
     paraver_configs/mpi/scalasca_properties/receives_from_late_sender.cfg\
     paraver_configs/mpi/scalasca_properties/receiving_from_latesender.cfg\
     paraver_configs/mpi/views/communication_phase_duration.cfg\
     paraver_configs/mpi/views/Activity_duration.cfg\
     paraver_configs/mpi/views/Outside_MPI.cfg\
     paraver_configs/mpi/views/point2point/p2p_send_size.cfg\
     paraver_configs/mpi/views/point2point/MPI_p2p_call.cfg\
     paraver_configs/mpi/views/point2point/p2p_recv_size.cfg\
     paraver_configs/mpi/views/point2point/MPICall_overhead.cfg\
     paraver_configs/mpi/views/point2point/s_r_bytes.cfg\
     paraver_configs/mpi/views/point2point/models/linear_model.cfg\
     paraver_configs/mpi/views/point2point/models/excess_time.cfg\
     paraver_configs/mpi/views/point2point/p2p_bytes_received.cfg\
     paraver_configs/mpi/views/point2point/p2p_size.cfg\
     paraver_configs/mpi/views/point2point/p2p_duration.cfg\
     paraver_configs/mpi/views/point2point/In_MPI_pt2pt_call.cfg\
     paraver_configs/mpi/views/point2point/total_msgs_in_transit.cfg\
     paraver_configs/mpi/views/point2point/p2p_bytes_sent.cfg\
     paraver_configs/mpi/views/point2point/destination_of_send.cfg\
     paraver_configs/mpi/views/point2point/iprobe_misses.cfg\
     paraver_configs/mpi/views/point2point/s_r_bandwidth.cfg\
     paraver_configs/mpi/views/point2point/nbprocs_in_pt2pt.cfg\
     paraver_configs/mpi/views/point2point/In_MPI_reception_call.cfg\
     paraver_configs/mpi/views/point2point/total_bytes_btw_events.cfg\
     paraver_configs/mpi/views/point2point/In_MPI_send_pt2pt_call.cfg\
     paraver_configs/mpi/views/point2point/outstanding_sends.cfg\
     paraver_configs/mpi/views/point2point/s_r_msgs.cfg\
     paraver_configs/mpi/views/point2point/to_whom_I_send.cfg\
     paraver_configs/mpi/views/point2point/total_bw.cfg\
     paraver_configs/mpi/views/point2point/iprobe_misses_per_ms.cfg\
     paraver_configs/mpi/views/point2point/source_of_reception.cfg\
     paraver_configs/mpi/views/point2point/advanced/In_long_receptions.cfg\
     paraver_configs/mpi/views/point2point/advanced/high_bw_process.cfg\
     paraver_configs/mpi/views/point2point/advanced/receiving_not_sending.cfg\
     paraver_configs/mpi/views/point2point/advanced/max_recBW_during_activity.cfg\
     paraver_configs/mpi/views/point2point/advanced/bytes_received_at_waits.cfg\
     paraver_configs/mpi/views/point2point/advanced/sending_not_receiving.cfg\
     paraver_configs/mpi/views/point2point/advanced/physical_s_r_msgs.cfg\
     paraver_configs/mpi/views/point2point/advanced/destination_last_large_send.cfg\
     paraver_configs/mpi/views/point2point/advanced/physical_s_r_bandwidth.cfg\
     paraver_configs/mpi/views/point2point/advanced/high_s_r_bandwidth.cfg\
     paraver_configs/mpi/views/point2point/nb_collective.cfg\
     paraver_configs/mpi/views/point2point/wait_type.cfg\
     paraver_configs/mpi/views/InMPI_mem_BW.cfg\
     paraver_configs/mpi/views/in_MPI_activity.cfg\
     paraver_configs/mpi/views/MPI_bandwidth.cfg\
     paraver_configs/mpi/views/msg_sizes.cfg\
     paraver_configs/mpi/views/MPI_activity.cfg\
     paraver_configs/mpi/views/In_MPI_call.cfg\
     paraver_configs/mpi/views/MPI_call_density.cfg\
     paraver_configs/mpi/views/MPI_call.cfg\
     paraver_configs/mpi/views/comm_size.cfg\
     paraver_configs/mpi/views/nb_active_processes.cfg\
     paraver_configs/mpi/views/nb_in_MPI.cfg\
     paraver_configs/mpi/views/communication_phase.cfg\
     paraver_configs/mpi/views/node_bandwidth.cfg\
     paraver_configs/mpi/views/Enumeration_of_MPI_calls.cfg\
     paraver_configs/mpi/views/MPI_call_duration.cfg\
     paraver_configs/mpi/views/advanced/total_bytes_in_transit.cfg\
     paraver_configs/mpi/views/advanced/receive_bandwidth_task.cfg\
     paraver_configs/mpi/views/advanced/long_MPI_calls.cfg\
     paraver_configs/mpi/views/advanced/messages_arriving.cfg\
     paraver_configs/mpi/views/advanced/total_sr_bw.cfg\
     paraver_configs/mpi/views/advanced/MPI_p2p.cfg\
     paraver_configs/mpi/views/advanced/receive_bandwidth_appl.cfg\
     paraver_configs/mpi/views/advanced/send_bandwidth_appl.cfg\
     paraver_configs/mpi/views/advanced/send_bandwidth.cfg\
     paraver_configs/mpi/views/advanced/bytes_sr_within_call.cfg\
     paraver_configs/mpi/views/advanced/From_where_mpi_calls.cfg\
     paraver_configs/mpi/views/advanced/MPIcall_cost.cfg\
     paraver_configs/mpi/views/advanced/MPIcall_duration.cfg\
     paraver_configs/mpi/views/advanced/in_MPI_call.cfg\
     paraver_configs/mpi/views/advanced/p2p_phase_duration.cfg\
     paraver_configs/mpi/views/advanced/MPIcall_cost_perbyte.cfg\
     paraver_configs/mpi/views/advanced/typeof_MPI_Wait.cfg\
     paraver_configs/mpi/views/advanced/MPI_Wait_from_Isend.cfg\
     paraver_configs/mpi/views/advanced/receive_bandwidth.cfg\
     paraver_configs/mpi/views/advanced/specific_MPI_duration.cfg\
     paraver_configs/mpi/views/advanced/bytes_outgoing.cfg\
     paraver_configs/mpi/views/advanced/send_bandwidth_task.cfg\
     paraver_configs/mpi/views/advanced/MPI_collectives.cfg\
     paraver_configs/mpi/views/advanced/Failed_tests.cfg\
     paraver_configs/mpi/views/advanced/2d_who_comms.cfg\
     paraver_configs/mpi/views/advanced/Isend_waits.cfg\
     paraver_configs/mpi/views/advanced/in_specific_MPI_call.cfg\
     paraver_configs/mpi/views/advanced/messages_outgoing.cfg\
     paraver_configs/mpi/views/advanced/bytespermsg.cfg\
     paraver_configs/mpi/views/advanced/total_sr_msgs.cfg\
     paraver_configs/mpi/views/advanced/bytes_arriving.cfg\
     paraver_configs/mpi/views/advanced/Who_calls_mpi.cfg\
     paraver_configs/mpi/views/advanced/sr_msgs.cfg\
     paraver_configs/mpi/views/advanced/bytesperMBS.cfg\
     paraver_configs/mpi/views/advanced/total_system_bw.cfg\
     paraver_configs/mpi/views/advanced/Failed_iprobes.cfg\
     paraver_configs/mpi/views/collectives/collective_duration.cfg\
     paraver_configs/mpi/views/collectives/nbprocs_in_colective.cfg\
     paraver_configs/mpi/views/collectives/communicator.cfg\
     paraver_configs/mpi/views/collectives/outside_collective.cfg\
     paraver_configs/mpi/views/collectives/collective_sizes.cfg\
     paraver_configs/mpi/views/collectives/collective_root.cfg\
     paraver_configs/mpi/views/collectives/MPI_collective_call.cfg\
     paraver_configs/mpi/views/collectives/advanced/Broadcast_number.cfg\
     paraver_configs/mpi/views/collectives/advanced/all2all_number.cfg\
     paraver_configs/mpi/views/collectives/enumerate_collectives.cfg\
     paraver_configs/mpi/sanity_checks/2d_compute_shifts.cfg\
     paraver_configs/mpi/sanity_checks/cloged_system.cfg\
     paraver_configs/mpi/sanity_checks/2dt_brwds_nbbwrds.cfg\
     paraver_configs/mpi/sanity_checks/duration_backwards_msg.cfg\
     paraver_configs/mpi/sanity_checks/2dt_backwards_time.cfg\
     paraver_configs/mpi/sanity_checks/src_backwards_msg.cfg\
     paraver_configs/mpi/sanity_checks/backward_msgs.cfg\
     paraver_configs/ompss/tasks/3dh_instr_task.cfg\
     paraver_configs/ompss/tasks/in_task.cfg\
     paraver_configs/ompss/tasks/task_name_and_location.cfg\
     paraver_configs/ompss/tasks/task_priority.cfg\
     paraver_configs/ompss/tasks/3dh_L2mr_task.cfg\
     paraver_configs/ompss/tasks/3dh_duration_task.cfg\
     paraver_configs/ompss/tasks/3dh_L2Tmr_task.cfg\
     paraver_configs/ompss/tasks/task_number.cfg\
     paraver_configs/ompss/tasks/3dh_ipc_task.cfg\
     paraver_configs/ompss/tasks/2dp_tasks.cfg\
     paraver_configs/ompss/tasks/task_numa_node.cfg\
     paraver_configs/ompss/tasks/task_and_deps.cfg\
     paraver_configs/ompss/tasks/nb_active_tasks.cfg\
     paraver_configs/ompss/tasks/2dp_concurrency_tasks.cfg\
     paraver_configs/ompss/worksharing_loops.cfg\
     paraver_configs/ompss/cuda/3dh_duration_CUDAruntime.cfg\
     paraver_configs/ompss/cuda/Non_overlapped_CUDA_Transfer_Direction.cfg\
     paraver_configs/ompss/cuda/CUDA_runtime.cfg\
     paraver_configs/ompss/cuda/cuda_transfers.cfg\
     paraver_configs/ompss/data_mgmgt/malloc_free_in_device.cfg\
     paraver_configs/ompss/data_mgmgt/nb_ongoing_transfers_duda.cfg\
     paraver_configs/ompss/data_mgmgt/aggregated_bandwidth.cfg\
     paraver_configs/ompss/data_mgmgt/2dh_bw2device.cfg\
     paraver_configs/ompss/data_mgmgt/direction_of_data_transfer_nosesiescorrecta.cfg\
     paraver_configs/ompss/data_mgmgt/bandwidth_per_device.cfg\
     paraver_configs/ompss/data_mgmgt/cache_waiting_for.cfg\
     paraver_configs/ompss/data_mgmgt/bytes_being_transfered.cfg\
     paraver_configs/ompss/data_mgmgt/data_tx.cfg\
     paraver_configs/ompss/general.cfg\
     paraver_configs/ompss/graph_and_scheduling/nb_tasks_in_graph.cfg\
     paraver_configs/ompss/graph_and_scheduling/2dp_order.cfg\
     paraver_configs/ompss/graph_and_scheduling/nb_ready_tasks.cfg\
     paraver_configs/ompss/graph_and_scheduling/creating_submitting_task.cfg\
     paraver_configs/ompss/graph_and_scheduling/versioning_sched.cfg\
     paraver_configs/ompss/opencl/opencl_runtime.cfg\
     paraver_configs/ompss/runtime/3dh_duration_state.cfg\
     paraver_configs/ompss/runtime/thread_state.cfg\
     paraver_configs/ompss/runtime/thread_state_with_locks.cfg\
     paraver_configs/ompss/runtime/thread_numa_node.cfg\
     paraver_configs/ompss/runtime/spins_yields.cfg\
     paraver_configs/ompss/runtime/average_sleep_time.cfg\
     paraver_configs/ompss/runtime/nanos_API.cfg\
     paraver_configs/ompss/runtime/nanos_locks.cfg\
     paraver_configs/ompss/runtime/waiting_task.cfg\
     paraver_configs/ompss/runtime/2dp_thread_state.cfg\
     paraver_configs/ompss/runtime/num_threads.cfg\
     paraver_configs/ompss/runtime/thread_cpuid.cfg\
     paraver_configs/ompss/runtime/async_thread_state.cfg\
     paraver_configs/ompss/2d_general.cfg\
     paraver_configs/general/link_to_source/by_call_stack/MPI_caller_line.cfg\
     paraver_configs/general/link_to_source/by_call_stack/MPI_caller.cfg\
     paraver_configs/general/link_to_source/by_call_stack/nbcalls_toMPI_per_uf.cfg\
     paraver_configs/general/link_to_source/by_call_stack/2dp_MPIcallertime.cfg\
     paraver_configs/general/link_to_source/by_call_stack/2dp_code_after_line.cfg\
     paraver_configs/general/link_to_source/by_call_stack/2dp_line_call.cfg\
     paraver_configs/general/link_to_source/by_call_stack/3dh_duration_MPIcallline.cfg\
     paraver_configs/general/link_to_source/by_call_stack/MPI_callers_4_levels.cfg\
     paraver_configs/general/link_to_source/by_call_stack/2dp_MPItime_line.cfg\
     paraver_configs/general/link_to_source/by_call_stack/3dp_MPItime_line.cfg\
     paraver_configs/general/analysis/2dp_uf.cfg\
     paraver_configs/general/analysis/3dh_instr_uf.cfg\
     paraver_configs/general/analysis/3dh_ipc_uf.cfg\
     paraver_configs/general/analysis/2dh_ipc.cfg\
     paraver_configs/general/analysis/2dp_useful.cfg\
     paraver_configs/general/analysis/2dh_L1Dmr.cfg\
     paraver_configs/general/analysis/2dh_usefultime.cfg\
     paraver_configs/general/analysis/Sup_model_data.cfg\
     paraver_configs/general/analysis/2dh_useful_instr.cfg\
     paraver_configs/general/analysis/3dh_duration_uf.cfg\
     paraver_configs/general/analysis/2dh_useful_MIPS.cfg\
     paraver_configs/general/analysis/2dh_ui.cfg\
     paraver_configs/general/analysis/efficiency.cfg\
     paraver_configs/general/analysis/advanced/3dc_instr_ipc_useful.cfg\
     paraver_configs/general/analysis/advanced/2dc_ud_ipc.cfg\
     paraver_configs/general/analysis/advanced/load_balance_for_specific_uf.cfg\
     paraver_configs/general/analysis/advanced/2dp_ufExcludingMPI.cfg\
     paraver_configs/general/analysis/advanced/2dc_cyc_ipc.cfg\
     paraver_configs/general/analysis/advanced/2dp_percentMPI_in_uf.cfg\
     paraver_configs/general/analysis/advanced/avg_procs.cfg\
     paraver_configs/general/analysis/advanced/3dh_ud_u.cfg\
     paraver_configs/general/analysis/advanced/2dc_ufduration_IPC.cfg\
     paraver_configs/general/analysis/advanced/3dh_usefulIPC_uf.cfg\
     paraver_configs/general/analysis/advanced/Sup_model_data.2.cfg\
     paraver_configs/general/analysis/advanced/3dp_ipc_useful.cfg\
     paraver_configs/general/analysis/advanced/3dc_usefulInstr_cycles_ipc.cfg\
     paraver_configs/general/analysis/Load_balance.cfg\
     paraver_configs/general/views/state_as_is.cfg\
     paraver_configs/general/views/state_duration.cfg\
     paraver_configs/general/views/not_useful.cfg\
     paraver_configs/general/views/user_function_nesting_level.cfg\
     paraver_configs/general/views/useful_duration.cfg\
     paraver_configs/general/views/not_running_duration.cfg\
     paraver_configs/general/views/user_functions_duration.cfg\
     paraver_configs/general/views/useful.cfg\
     paraver_configs/general/views/user_functions.cfg\
     paraver_configs/general/views/user_calls_duration.cfg\
     paraver_configs/general/views/instantaneous_parallelism.cfg\
     paraver_configs/general/views/user_calls.cfg\
     paraver_configs/general/views/User_function_excl_MPI.cfg\
     paraver_configs/general/views/one.cfg\
     paraver_configs/general/sanity_checks/preempted_time_in_useful.cfg\
     paraver_configs/general/sanity_checks/preempted_time_outside_useful.cfg\
     paraver_configs/general/sanity_checks/Events_too_close.cfg\
     paraver_configs/general/sanity_checks/flushing.cfg\
     paraver_configs/general/sanity_checks/2dh_cycperus.cfg\
     paraver_configs/general/sanity_checks/Equivalent_CPUs.cfg\
     paraver_configs/general/2dp_WhereMyNextTaskWasGenerated.cfg\
     paraver_configs/cluster/network_transfers_and_bw.cfg\
     $(END)
