#!/bin/bash
#/*************************************************************************************/
#/*      Copyright 2009 Barcelona Supercomputing Center                               */
#/*                                                                                   */
#/*      This file is part of the NANOS++ library.                                    */
#/*                                                                                   */
#/*      NANOS++ is free software: you can redistribute it and/or modify              */
#/*      it under the terms of the GNU Lesser General Public License as published by  */
#/*      the Free Software Foundation, either version 3 of the License, or            */
#/*      (at your option) any later version.                                          */
#/*                                                                                   */
#/*      NANOS++ is distributed in the hope that it will be useful,                   */
#/*      but WITHOUT ANY WARRANTY; without even the implied warranty of               */
#/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                */
#/*      GNU Lesser General Public License for more details.                          */
#/*                                                                                   */
#/*      You should have received a copy of the GNU Lesser General Public License     */
#/*      along with NANOS++.  If not, see <http://www.gnu.org/licenses/>.             */
#/*************************************************************************************/

BASE_DIR=$(dirname $0)/

args=""
program=""

while [ "$1" ]; do
  case $1 in
    "--ins" | "--instrument")
      program="nanox-ins"
      shift
      ;;
    "--pfm" | "--performance")
      program="nanox-pfm"
      shift
      ;;
    "--dbg" | "--debug")
      program="nanox-dbg"
      shift
      ;;
    "--ins-dbg" | "--instrument --debug" | "--debug --instrument")
      program="nanox-ins-dbg"
      shift
      ;;
    *)
      args+=$1
      shift    
      ;;
  esac
done

if [ x$program = x ]; then
  if test -e $BASE_DIR/nanox-pfm; then
    program="nanox-pfm"
  elif test -e $BASE_DIR/nanox-dbg; then
    program="nanox-dbg"
  elif test -e $BASE_DIR/nanox-ins; then
    program="nanox-ins"
  elif test -e $BASE_DIR/nanox-ins-dbg; then
    program="nanox-ins-dbg"
  else
    program="xxx"
  fi
fi

if test -e $BASE_DIR/$program; then
  $BASE_DIR/$program $args
else
  echo "Nanox: Cannot find nanox back-end utility!"
  exit 0
fi

